# Generated by Django 5.2.8 on 2025-11-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='products.product'),
        ),
    ]
